name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat version
        run: swiftformat --version
      - name: Format lint
        run: swiftformat --lint .
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint version
        run: swiftlint --version
      - name: Lint
        run: swiftlint lint --quiet
  test:
    runs-on: macos-15
    environment: default
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: swift test --enable-code-coverage
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/CoreDataRepositoryPackageTests.xctest/Contents/MacOS/CoreDataRepositoryPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
